/* Profile table 1 row
link table many rows */

CREATE TABLE IF NOT EXISTS profile (
    id INT PRIMARY KEY AUTO_INCREMENT,
    display_name VARCHAR(100) NOT NULL,
    bio TEXT NULL, 
    a_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS links (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    l_url VARCHAR(255) NOT NULL,
    position INT NOT NULL,
    on_off BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS boxes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    position INT NOT NULL DEFAULT 0,
    on_off BOOLEAN NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

/* Add admin account 1 row EVER */

CREATE TABLE IF NOT EXISTS admin (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);

/* add box editing */

ALTER TABLE boxes 
ADD COLUMN size VARCHAR(5) NOT NULL DEFAULT '1x1';


ALTER TABLE boxes
ADD COLUMN grid_x INT NOT NULL DEFAULT 1,
ADD COLUMN grid_y INT NOT NULL DEFAULT 1,
ADD COLUMN grid_w INT NOT NULL DEFAULT 1,
ADD COLUMN grid_h INT NOT NULL DEFAULT 1;